"""Integration tests for the PyWriter distributions.

Test the .docx "proof read" scripts generated by inliner.py. 

For further information see https://github.com/peter88213/PyWriter
Published under the MIT License (https://opensource.org/licenses/mit-license.php)
"""
import os
import unittest
import zipfile

from pywriter.converter.yw7cnv import Yw7Cnv
from pywriter.model.yw7file import Yw7File

from pywriter.model.officefile import OfficeFile


TEST_PATH = os.getcwd()
EXEC_PATH = 'yw7/'
DATA_PATH = 'data/office/'

TEST_DOCUMENT = EXEC_PATH + 'yw7 Sample Project.docx'
DOCUMENT_CONTENT = 'word/document.xml'
PROOFED_DOCUMENT = DATA_PATH + 'proofed.docx'

TEST_YW7 = EXEC_PATH + 'yw7 Sample Project.yw7'
REFERENCE_YW7 = DATA_PATH + 'normal.yw7'
PROOFED_YW7 = DATA_PATH + 'proofed.yw7'

with open(REFERENCE_YW7, 'r') as f:
    TOTAL_SCENES = f.read().count('<SCENE>')


def read_file(inputFile):
    with open(inputFile, 'r', encoding='utf-8') as f:
        return(f.read())


def copy_file(inputFile, outputFile):
    with open(inputFile, 'rb') as f:
        myData = f.read()
    with open(outputFile, 'wb') as f:
        f.write(myData)
    return()


def remove_all_testfiles():
    try:
        os.remove(TEST_DOCUMENT)
    except:
        pass
    try:
        os.remove(TEST_YW7)
    except:
        pass
    try:
        os.remove(EXEC_PATH + DOCUMENT_CONTENT)
    except:
        pass
    try:
        os.rmdir(EXEC_PATH + '/word')
    except:
        pass


class NrmOpr(unittest.TestCase):
    """Test case: Normal operation

        Condition: yw7 file is present and read/writeable. 
        Expected result: During the whole process, the intermediate
                    markdown file content matches 
                    the corresponding reference string. 
    """

    def setUp(self):
        remove_all_testfiles()
        copy_file(REFERENCE_YW7, TEST_YW7)

    def test_data(self):
        """Verify test data integrity. """
        self.assertNotEqual(
            read_file(REFERENCE_YW7),
            read_file(PROOFED_YW7))

    def test_yw7_to_docx(self):
        """Convert markdown to docx. """

        yw7File = Yw7File(TEST_YW7)
        documentFile = OfficeFile(TEST_DOCUMENT)
        converter = Yw7Cnv()

        self.assertEqual(converter.yw7_to_document(
            yw7File, documentFile), 'SUCCESS: "' + TEST_DOCUMENT + '" saved.')

        with zipfile.ZipFile(TEST_DOCUMENT, 'r') as myzip:
            myzip.extract(DOCUMENT_CONTENT, EXEC_PATH)
            myzip.close

        self.assertEqual(read_file(EXEC_PATH + DOCUMENT_CONTENT),
                         read_file(DATA_PATH + DOCUMENT_CONTENT))

    def test_docx_to_yw7(self):
        """Convert docx to markdown. """

        copy_file(PROOFED_DOCUMENT, TEST_DOCUMENT)

        yw7File = Yw7File(TEST_YW7)
        documentFile = OfficeFile(TEST_DOCUMENT)
        converter = Yw7Cnv()

        self.assertEqual(converter.document_to_yw7(documentFile, yw7File), 'SUCCESS: ' + str(
            TOTAL_SCENES) + ' Scenes written to "' + TEST_YW7 + '".')

        self.assertEqual(read_file(TEST_YW7),
                         read_file(PROOFED_YW7))

    def tearDown(self):
        remove_all_testfiles()


def main():
    unittest.main()


if __name__ == '__main__':
    main()
