@startuml
create export_odt.py

create "ui : UiTk"
export_odt.py ->> "ui : UiTk" : UiTk()

create "converter : Yw7Converter" as converter 
export_odt.py ->> converter : Yw7Converter()

create "exportSourceFactory : ExportSourceFactory" as exportSourceFactory
converter ->> exportSourceFactory : ExportSourceFactory(fileClasses)

create "exportTargetFactory : ExportTargetFactory" as exportTargetFactory 
converter ->> exportTargetFactory : ExportTargetFactory(fileClasses)

create "importSourceFactory : ImportSourceFactory" as importSourceFactory 
converter ->> importSourceFactory : ImportSourceFactory(fileClasses)

create "importTargetFactory : ImportTargetFactory" as importTargetFactory 
converter ->> importTargetFactory : ImportTargetFactory(fileClasses)

create "newProjectFactory : NewProjectFactory" as newProjectFactory 
converter ->> newProjectFactory : NewProjectFactory(fileClasses)

export_odt.py ->> converter : run(sourcePath, **kwargs)

activate converter
converter ->> exportSourceFactory : make_file_objects(sourcePath, **kwargs)

activate exportSourceFactory
create "source : Yw7File" as source
exportSourceFactory ->> source : Yw7File()
exportSourceFactory -->> converter : message, source
deactivate exportSourceFactory

converter ->> exportTargetFactory : make_file_objects(sourcePath, **kwargs)

activate exportTargetFactory
create "target : OdtExport" as target
exportTargetFactory ->> target : OdtExport()
exportTargetFactory -->> converter : message, target
deactivate exportTargetFactory

converter ->> converter : export_from_yw(source, target)
activate converter
converter ->> "ui : UiTk" : set_info_what(message)
converter ->> converter : convert(source, target)
activate converter

converter ->> source : read()
activate source
source -->> converter : message
deactivate source

converter ->> target : merge(source)
activate target
target -->>  converter : message
deactivate target

converter ->> target : write()
activate target
target -->>  converter : message
deactivate converter
deactivate target

converter ->> "ui : UiTk" : set_info_how(message)
deactivate converter
deactivate converter

export_odt.py ->> "ui : UiTk" : start()
@enduml