@startuml
create cnv_proof.py as script

create "ui : UiTk"
script ->> "ui : UiTk" : UiTk()

create "converter : Yw7Converter" as converter 
script ->> converter : Yw7Converter()

create "exportSourceFactory : ExportSourceFactory" as exportSourceFactory
converter ->> exportSourceFactory : ExportSourceFactory(fileClasses)

create "exportTargetFactory : ExportTargetFactory" as exportTargetFactory 
converter ->> exportTargetFactory : ExportTargetFactory(fileClasses)

create "importSourceFactory : ImportSourceFactory" as importSourceFactory 
converter ->> importSourceFactory : ImportSourceFactory(fileClasses)

create "importTargetFactory : ImportTargetFactory" as importTargetFactory 
converter ->> importTargetFactory : ImportTargetFactory(fileClasses)

create "newProjectFactory : NewProjectFactory" as newProjectFactory 
converter ->> newProjectFactory : NewProjectFactory(fileClasses)

script ->> converter : run(sourcePath, **kwargs)

activate converter
converter ->> exportSourceFactory : make_file_objects(sourcePath, **kwargs)

activate exportSourceFactory
exportSourceFactory -->> converter : exception
deactivate exportSourceFactory

converter ->> importSourceFactory : make_file_objects(sourcePath, **kwargs)

activate importSourceFactory
create "source : HtmlProof" as source
importSourceFactory ->> source : HtmlProof()
importSourceFactory -->> converter : source
deactivate importSourceFactory

converter ->> importTargetFactory : make_file_objects(sourcePath, **kwargs)

activate importTargetFactory
create "target : Yw7File" as target
importTargetFactory ->> target : Yw7File()
importTargetFactory -->> converter : target
deactivate importTargetFactory

converter ->> converter : import_to_yw(source, target)
activate converter
converter ->> "ui : UiTk" : set_info_what(message)

converter ->> target : read()
activate target
target -->> converter
deactivate target

converter ->> source : read()
activate source
source -->> converter
deactivate source

converter ->> target : write()
activate target
target -->> converter
deactivate target

converter ->> "ui : UiTk" : set_info_how(message)
deactivate converter
deactivate converter

script ->> "ui : UiTk" : start()
@enduml